### ISSUE TITLE
Spike: validate need of attendance table

### ISSUE THREAD

**Issue by MichelRogov** [MichelRogov/Accounting#35]
A.C. 
technical specification for lesson - attendance composition. 
Questions:
Do we need an extra table for attendance or we can put all attended users to List?
Will it affects getting a statistics per user \ per group?
Other questions?

**Comment by maximorlenco** [comment]
Having considered this question from different angles, I came to the conclusion that the best option for us is to leave the `Attendance` table.
Because :

-We will need statistics on the entire course.
- Student attendance statistics.
- Considering that not only students of one group can attend the lesson, there will also be a more convenient option with a separate table for attendance.
-In the case of  `List <User> `
attendance in Lesson, in order to get information on the attendance of a particular student, we will have to go through all the `Lists` in all the lessons, which will be spent extra resources.
- From the `Attendance` table, we will be more convenient and optimal at the cost of resources data acquisition 
both as an individual student and throughout the course
(Through one request we will get all the information)
